export const AppConfig = {
  metadata: {
    defaultTitle: "Example app",
    defaultDescription: "Generated by create next app",
    publicUrl: "https://example.com",
    keywords: ["nextjs", "template"],
  },
  footerLinks: [
    { label: "privacy", link: "#" },
    { label: "terms", link: "#" },
    { label: "about", link: "#" },
  ],
  auth: {
    signInRedirectUrl: "/home", // redirect to this url after login
    signOutRedirectUrl: "/", // redirect to this url after logout
    signInPage: "/auth/login", // login page
  },
  maintenance: {
    enabled: (process.env.MAINTENANCE_ENABLED ?? "false") === "true",
    path: "/maintenance",
  },
}
