export const AppConfig  = {
  metadata: {
    defaultTitle: 'Example app',
    defaultDescription: 'Generated by create next app',
    publicUrl: 'https://example.com',
    keywords: ['nextjs', 'template']
  },
  footerLinks: [
    {label: 'privacy', link: '#'},
    {label: 'terms', link: '#'},
    {label: 'about', link: '#'},
  ]
}